"""initial schema

Revision ID: 28be1ddbc533
Revises:
Create Date: 2026-10-06 00:47:01.687216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28be1ddbc533'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_caller',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('allowed_skills', sa.JSON(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('daily_spend_cap_usd', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('clinic',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('booking_style', sa.String(length=10), nullable=False),
    sa.Column('emergency_numbers', sa.JSON(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("booking_style IN ('timed','token')", name='ck_clinic_booking_style'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_type',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('fee_inr', sa.Integer(), nullable=False),
    sa.CheckConstraint('fee_inr >= 0', name='ck_appt_type_fee'),
    sa.CheckConstraint('minutes > 0', name='ck_appt_type_minutes'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'name', name='uq_appt_type_name')
    )
    with op.batch_alter_table('appointment_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_type_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('doctor',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.Column('breaks', sa.JSON(), nullable=False),
    sa.Column('leave', sa.JSON(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('avg_consult_min', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('onboarding_draft',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('tavily_sources', sa.JSON(), nullable=False),
    sa.Column('extracted_json', sa.JSON(), nullable=False),
    sa.Column('review_notes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'phone', 'name', name='uq_patient_identity')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('appointment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('doctor_id', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_no', sa.Integer(), nullable=True),
    sa.Column('reason_short', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urgent_by_staff', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('a2a_caller_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('web','voice','a2a','staff')", name='ck_appt_source'),
    sa.CheckConstraint("status IN ('held','confirmed','checked_in','completed','cancelled','no_show')", name='ck_appt_status'),
    sa.CheckConstraint('"end" > start', name='ck_appt_time_order'),
    sa.ForeignKeyConstraint(['a2a_caller_id'], ['a2a_caller.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['appointment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index('ix_appt_doctor_start', ['doctor_id', 'start'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('a2a_context_id', sa.String(length=64), nullable=True),
    sa.Column('transcript_masked', sa.JSON(), nullable=False),
    sa.Column('handoff', sa.Boolean(), nullable=False),
    sa.Column('emergency_flag', sa.Boolean(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_a2a_context_id'), ['a2a_context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('routing_rule',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinic_id', sa.String(length=32), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.String(length=32), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_rule_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('waitlist_entry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('doctor_id', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['appointment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entry_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('guardrail_event',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('rail', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardrail_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardrail_event_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardrail_event_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('llm_call',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('span_id', sa.String(length=16), nullable=True),
    sa.Column('node', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=8), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('appointment_id', sa.String(length=32), nullable=False),
    sa.Column('amount_inr', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_appointment_id'), ['appointment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_appointment_id'))

    op.drop_table('payment')
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_at'))

    op.drop_table('llm_call')
    with op.batch_alter_table('guardrail_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardrail_event_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_guardrail_event_at'))

    op.drop_table('guardrail_event')
    with op.batch_alter_table('waitlist_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entry_doctor_id'))

    op.drop_table('waitlist_entry')
    with op.batch_alter_table('routing_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_rule_clinic_id'))

    op.drop_table('routing_rule')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_a2a_context_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('ix_appt_doctor_start')

    op.drop_table('appointment')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_clinic_id'))

    op.drop_table('patient')
    op.drop_table('onboarding_draft')
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_clinic_id'))

    op.drop_table('doctor')
    with op.batch_alter_table('appointment_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_type_clinic_id'))

    op.drop_table('appointment_type')
    op.drop_table('clinic')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('a2a_caller')
    # ### end Alembic commands ###
