"""consult times, doctor booking style, routing priority

Revision ID: 5281dfa49c85
Revises: 28be1ddbc533
Create Date: 2026-10-07 02:19:39.096851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5281dfa49c85'
down_revision: Union[str, Sequence[str], None] = '28be1ddbc533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointment', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctor', sa.Column('booking_style', sa.String(length=10), nullable=True))
    op.add_column('routing_rule', sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routing_rule', 'priority')
    op.drop_column('doctor', 'booking_style')
    op.drop_column('appointment', 'completed_at')
    op.drop_column('appointment', 'started_at')
    # ### end Alembic commands ###
